language: cpp
os: windows
branches:
  only:
    - master
env:
  - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
script:
  - export PATH=$MSBUILD_PATH:$PATH
  - curl -O https://www.asus.com/campaign/aura/download/AuraSDK.zip
  - 7z x AuraSDK.zip -oAuraSDK
  - MSBuild.exe AuraD.sln -t:Clean -t:Build -p:Configuration=CI
  - 7z a -tzip AuraD.zip ./CI/AuraD.exe ./AuraSDK/sdk/AURA_SDK.dll
deploy:
  name: Build $(git describe --abbrev=0)
  api_key: 
    secure: ey9nr4IHSw8gZfBH7Wrv9pblsZVcyEnrcACL6UGeoUFgQ1xPgTcv5l3HAkHyFtopOkErduy2wmdWFG6E7Z3ZAiGtocuA8DYmXf2YBXvQ9tiImackIObSoM4orDHpTKAd7NXMf0xh9fCQ5R2C4s73JrdeGqoVdZ5EY+ClSYu4DRtC32i0FZSeu5PLbpXHNEQscJnHQm2zp79hrZQK/DNOja6h3+Yta0E/o+OSpv7dZ6SbT2OW6nst4PWuSAAEw1vpMSYWjJkvWE5H7USOPe165YmewZTjNNBRZ1LmvEPFWcUQLlVNNrb2TEJmvJJ/95gawZAtYsbrKM5JggBT6CeopvVWOM6QEoPsBkwgfNFhGLSbXS9J/ZZ8Rep++BT34iZSPLiBz8QfiII0eSfsqWta2JVcQb05toFFTzRdEApoFemLpdokJ8ztBh9QpnqYDA/SYHhgMn75DWSdNy2P/+Em9q5JHxptGEgi+Lhm+06tup37BA0HKe0tZIQHio9WP39pKHuyOS8FxCz+SRE3PCafXyjszAKrY+VUkAFxe1bkU0gta94MdXTIxEF5PpNmKzBAnMdlluQEeuEZHrQmqp2xtegKx63gnWXRSACzaieW5xgvapRtHwcrPRVRiQUPHddgpt7WHuELbRWZ/8H0b/pk5dAMXIc2yEGaWm48tL+fB3Q=
  provider: releases
  file:
    - AuraD.zip
  skip_cleanup: true
  on:
    branch: master
