language: cpp
os: windows
branches:
  only:
    - master
env:
  - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
script:
  - export PATH=$MSBUILD_PATH:$PATH
  - curl -O https://www.asus.com/campaign/aura/download/AuraSDK.zip
  - 7z x AuraSDK.zip -oAuraSDK
  - MSBuild.exe AuraD.sln -t:Clean -t:Build -p:Configuration=CI
  - 7z a -tzip AuraD.zip ./CI/AuraD.exe ./AuraSDK/sdk/AURA_SDK.dll
deploy:
  name: Build $(git describe --abbrev=0)
  api_key: $(API_KEY)
  provider: releases
  file:
    - AuraD.zip
  skip_cleanup: true
  on:
    branch: master
